### ISSUE TITLE
parallelMap failed when use facades or helper functions  in function body

### ISSUE THREAD

**Issue by Insolita** [spatie/laravel-collection-macros#108]
I'm not sure that this is a bug, but I think this should be mentioned in the documentation

Failed examples
```php
   $result = collect([1, 2, 3])->parallelMap(function ($value) {
                return [Hash::make($value)=>$value];
            }, 3);
```

```php
$result = collect([1, 2, 3])->parallelMap(function ($value) {
                return $value * config('algo.coefficient');
            }, 3);
```
(This trouble solved by registration values/functions in class context)

This is valid example

```php
class Parallel {
     private $coefficient;
     private $hasher;
     public function __construct(BcryptHasher $hasher)
    {
        $this->hasher = $hasher;
        $this->coefficient =  config('algo.coefficient');
     }

     public function run()
    {
         return collect([1, 2, 3])->parallelMap(function ($value) {
                  return [$this->hasher->make($value)=> $value * $this->coefficient];
         }, 3);
     }
}
```

**Comment by brendt** [comment]
@Insolita It would be helpful to see the error output. 

Because `parallelMap` will use a child process to run tasks, it's possible that not exactly the same context is used as available in the parent process. Eg. if Laravel isn't bootstrapped correctly in a child process, chances are Facades break. The underlying package `amp/parallel` tries to automatically bootstrap an environment as close as possible. 

That being said, if you have the error output we'll probably know more specifically what's wrong.

**Comment by kmuenkel** [comment]
The problem is the App instance falls out of scope when the handler Closure gets serialized, so Laravel abstractions become unusable therein. Additionally, Model classes need some special handling when it comes to reconnecting with the database, so if you include any in your Closure's static variables, they won't work properly.

Fortunately, Laravel already figured out how to handle these issues in the context of PhpUnit tests and Queued Jobs, respectively. Specifically, the CreatesApplication and SerializesAndRestoresModelIdentifiers traits. So I've created a wrapper package around this package that leverages those traits to integrates it with Laravel a little better.

https://github.com/kmuenkel/parallel-collection
